server:
  port: 8006
spring:
  application:
    name: cloud-provider-payment #指定服务名称
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # 服务注册的地址
        service-url: http://${spring.cloud.consul.host}:${spring.cloud.consul.port}
        # 服务注册的ip地址
        prefer-ip-address: true
