server:
  port: 7002
spring:
  application:
    name: eureka-server7002 #指定服务名称
#eureka:
#  instance:
#    hostname: eureka7002.com #指定主机地址
#  client:
#    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
#    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
#  server-url:
##    enable-self-preservation: false #关闭保护模式
#    defaultZone: http://eureka7001.com:7001/eureka/ #指定注册中心地址



eureka:
  instance:
    hostname: eureka7002.com    #eureka服务端的实例名字
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/

