server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider #指定服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址


  datasource:
    url: jdbc:mysql://localhost:3306/aixdl?userSSL=false&c har acterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 19750424
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


management:
  endpoints:
    web:
      exposure:
        include: '*'